### ISSUE TITLE
2.2.0 gives "regexps is not defined" error

### ISSUE THREAD

**Issue by speedfirst** [3rd-Eden/useragent#113]
once `require('useragent')()`, you will see

```json
ReferenceError: regexps is not defined
    at updating (/------/node_modules/useragent/index.js:22:15)
    at parsing (//------/node_modules/useragent/lib/update.js:39:11)
    at Object.generate (/------/node_modules/useragent/lib/update.js:214:3)
    at Object.parse (/------/node_modules/useragent/lib/update.js:174:11)
    at reading (/------/node_modules/useragent/lib/update.js:38:17)
    at /------/node_modules/async-listener/glue.js:188:31
    at tryToString (fs.js:499:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:487:12)
```

my node is v8.0.0

after rolling back to v2.1.13, it works

**Comment by jwarkentin** [comment]
Yeah, this version is completely broken. Crashes my app the moment it starts due to the missing variable declaration. 6b84fdbd49ea20cb11ea3513ce69533f1164031d is the commit that broke it.

**Comment by 26medias** [comment]
It's been 5 days.
Will the author fix it?

**Comment by 3rd-Eden** [comment]
Author is looking at various of options.

**Comment by speedfirst** [comment]
Wondering why this broken version can pass tests ?

**Comment by 3rd-Eden** [comment]
There is no test for auto update because it depends on an external data source that doesn't always change making it impossible to create a test that always works when you run it.

**Comment by 3rd-Eden** [comment]
Fixed in latest
